### ISSUE TITLE
cpy-cli fails to copy a folder recursively

### ISSUE THREAD

**Issue by indfnzo** [kentcdodds/nps-utils#20]
Can't seem to copy folders with subfolders recursively using the built-in [cpy-cli](https://github.com/sindresorhus/cpy-cli). See https://github.com/sindresorhus/cpy-cli/issues/10.

Project is running on Windows.

**Comment by indfnzo** [comment]
Since apparently, cpy [doesn't currently support recursive copying](https://github.com/sindresorhus/cpy/issues/40#issuecomment-265864426), would it be possible to somehow switch providers from cpy-cli to [ncp](https://github.com/AvianFlu/ncp)? Or maybe we could simply create a new util (say, `ncopy`), referencing ncp via cli.

Another alternative: a wrapper for [fs-extra](https://github.com/jprichardson/node-fs-extra) as nps utils.

**Comment by indfnzo** [comment]
Update: I have a working setup with `ncopy` exported as another utility under nps-utils. I use it like so:

```javascript
const { series, ncp } = require('nps-utils');

module.exports = {
    scripts: {
        someScript: series(
            ( ... ),
            ncp('dist dist2')
        )
    }
}
```

This successfully copies all contents of `dist` onto `dist2`, including subfolders and files inside subfolders.

If you're fine with this implementation, I can make a PR to get this merged.

**Comment by kentcdodds** [comment]
That looks good to me! Feel free to make a pull request 👍
Be sure to include tests and docs 😀

**Comment by kentcdodds** [comment]
And thank you!
