### ISSUE TITLE
export getBin, but without prepending node

### ISSUE THREAD

**Issue by wmertens** [kentcdodds/nps-utils#29]
It would be nice to be able to get the path to a binfile of a package. `getBin` is not exported, but it also prepends `node`.

So I propose adding ``const runBin = (...args) => `node ${getBin(...args)}` `` internally and exporting `getBin`

My very specific use case would be to be able to run Jest under `ndb` like

```js
const {getBin} = require('nps-utils')

module.exports = {
 test: {
   inspect: `ndb ${getBin('jest')} --runInBand`
 }
}
```

**Comment by kentcdodds** [comment]
PRs welcome 👍
