### ISSUE TITLE
Feature: better documentation

### ISSUE THREAD

**Issue by morgs32** [kentcdodds/nps-utils#31]
Accidentally created the issue before writing the description. 
So:
1. This doesn't work for me. https://doclets.io/kentcdodds/nps-utils/master
    - Once it loads (which takes a few) I can't navigate around it without getting a 502.
2. This generated documentation is sub par: https://doc.esdoc.org/github.com/kentcdodds/nps-utils/function/index.html#static-function-crossEnv
   -  It's probably convenient to run (in CI/CD process). It's **maybe** convenient for you to maintain? But more important than all that is it's just not as intelligible as we (the greater community) has come to expect from senior engineers such as yourself. I mean that with respect of course.

If you would like me to volunteer, I would help you redo it. Gitbooks, a nextjs app, whatever you want.

**Comment by kentcdodds** [comment]
Hi @morgs32 👋

I'm looking forward to your PRs 😄

Update:

Yeah, I agree the esdoc thing doesn't work well at all. I'd rather just move everything to the README. Would you like to do that?

**Comment by morgs32** [comment]
~Yes I'll give that a shot!~
I didn't have as much need for this as I thought. I presume I'm not the only one?
